name: vistaar_assignment_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.6.1
  device_preview: ^1.1.0
  shared_preferences: ^2.0.17
  flutter_riverpod: ^2.1.3
  dio: ^4.0.6
  auto_size_text: ^3.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

